export default {
  SET_TOAST: 'TOAST/SET',
  SET_INFO_TOAST: 'TOAST/INFO/SET',
  SET_SUCCESS_TOAST: 'TOAST/SUCCESS/SET',
  SET_WARNING_TOAST: 'TOAST/WARNING/SET',
  SET_ERROR_TOAST: 'TOAST/ERROR/SET',
  UNSET_TOAST: 'TOAST/UNSET'
}
